### ISSUE TITLE
阿里短信的jar拉取出错

### ISSUE THREAD

**Issue by 15863004186sunchi** [514840279/danyuan-application#3]
构建失败，因为拉取的tao-bao-sdk的校验和不对，后续的使用该jar包的代码直接报错

**Comment by 514840279** [comment]
项目上 /lib 文件夹，里面有阿里的短信jar包，执行bat里面的导入语句，导入到你的maven本地仓库吧，这个包我找了，并没有发现那个公共仓库下有，所以我下在的单独的包放到项目中了，bat执行并不好用，需要copy里面的语句在命令行中执行，前提你的java ，maven都要配置环境变量，

**Comment by 514840279** [comment]
阿里短信整合到了阿里云上，jar包可以直接引入
               &lt;!-- 阿里大于 短信服务 -->
		&lt;dependency&gt;
			&lt;groupId&gt;com.aliyun&lt;/groupId&gt;
			&lt;artifactId&gt;aliyun-java-sdk-core&lt;/artifactId&gt;
			&lt;version&gt;3.3.1&lt;/version&gt;
                  <!-- 注：如提示报错，先升级基础包版，无法解决可联系技术支持 --&gt;
		&lt;/dependency&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;com.aliyun&lt;/groupId&gt;
			&lt;artifactId&gt;aliyun-java-sdk-dysmsapi&lt;/artifactId&gt;
			&lt;version&gt;1.1.0&lt;/version&gt;
		&lt;/dependency&gt;

但是需要注意 版本用3.3.1 不要升级，最新的3.3.3 有路径错误，发送代码基本和之前一样。
阿里云短信服务： https://help.aliyun.com/document_detail/55359.html?spm=a2c4g.11186623.6.588.7f552e791cAYnV
